paths:
  /api/products:
    post:
      summary: Create a product
      tags:
        - Products
      responses:
        '200':
          description: Create product
        '500':
          description: Server error
        '400':
          description: Missing data
  /api/products/getAll:
    get:
      summary: Get all products
      tags:
       - Products
      responses:
        '200':
          description: All products
        '500':
          description: Server error
        '400':
          description: Missing data
  /api/products/{productId}:
    get:
      summary: Get a product by id
      tags:
        - Products
      parameters:
      - name: productId
        in: path
        description: Product identifier
      responses:
        '200':
          description: One product
        '500':
          description: Server error
        '400':
          description: Missing data